In [1]:
count=0
while(count<3):
    count=count+1
    print("Hello world")

Hello world
Hello world
Hello world


In [2]:
for i in range(1, 5):
 for j in range(i):
     print(i, end=' ',)
 print()

1 
2 2 
3 3 3 
4 4 4 4 


In [3]:
for letter in 'pythonforpython':
 if letter == 'y' or letter == 'o':
     continue
     print('Current Letter :', letter)

In [4]:
names=['ababe','kebede','almaz','alemu']
print(names)

['ababe', 'kebede', 'almaz', 'alemu']


In [5]:
names[0]='bezawit'

In [6]:
print(names)

['bezawit', 'kebede', 'almaz', 'alemu']


In [7]:
names.append('solomon')

In [8]:
print(names)

['bezawit', 'kebede', 'almaz', 'alemu', 'solomon']


In [9]:
names.insert(0,'Haile')

In [10]:
print(names)

['Haile', 'bezawit', 'kebede', 'almaz', 'alemu', 'solomon']


In [11]:
number=[1,2,3,4,5,76]

In [12]:
print(number)

[1, 2, 3, 4, 5, 76]


In [13]:
names.extend(number)

In [14]:
print(names)

['Haile', 'bezawit', 'kebede', 'almaz', 'alemu', 'solomon', 1, 2, 3, 4, 5, 76]


In [15]:
number

[1, 2, 3, 4, 5, 76]

In [16]:
number.extend(names)

In [17]:
print(number)

[1, 2, 3, 4, 5, 76, 'Haile', 'bezawit', 'kebede', 'almaz', 'alemu', 'solomon', 1, 2, 3, 4, 5, 76]


In [18]:
number.pop()
number.pop()
number.pop()
number.pop()
number.pop()

2

In [19]:
print(number)

[1, 2, 3, 4, 5, 76, 'Haile', 'bezawit', 'kebede', 'almaz', 'alemu', 'solomon', 1]


In [20]:
print(number)

[1, 2, 3, 4, 5, 76, 'Haile', 'bezawit', 'kebede', 'almaz', 'alemu', 'solomon', 1]


In [21]:
number.pop()
number.pop()
number.pop()
number.pop()
number.pop()

'kebede'

In [22]:
print(number)

[1, 2, 3, 4, 5, 76, 'Haile', 'bezawit']


In [23]:
number.pop(0)

1

In [24]:
print(number)

[2, 3, 4, 5, 76, 'Haile', 'bezawit']


In [25]:
# Lambeda function
c = [1, 2, 3, 4, 5, 6]
even=filter(lambda x:x%2==0,c)
print(list(even))

[2, 4, 6]


In [26]:
hello=filter(lambda Y:Y%2==0 , c)
print(list(hello))

[2, 4, 6]


In [27]:
double=map(lambda X:X*2,c)
print(list(double))

[2, 4, 6, 8, 10, 12]


In [28]:
def abe():
    """This function performs Gretting"""
    print("Hello , Abe!")
abe()

Hello , Abe!


In [29]:
def evenOdd(y):
    if(y%2==0):
        return "Even" 
    else:
        return "Odd" 
print(evenOdd(10))

Even


In [30]:
def myFun(x, y=50):
    print("x: ", x)
    print("y: ", y)
myFun(10)

x:  10
y:  50


In [31]:
# List comprehenssion 
data = [1, 2, 3, 4, 5, 6, 7, 8]
result=[value**2+value/2 for value in data]
print(result)

[1.5, 5.0, 10.5, 18.0, 27.5, 39.0, 52.5, 68.0]


In [32]:
datas=[2,3,4,5]
double=[val*2 for val in datas]
print(double)

[4, 6, 8, 10]


In [33]:
result=[value for value in range (0,15) if value%2==0]
print(result)

[0, 2, 4, 6, 8, 10, 12, 14]


In [34]:
text="Addis Ababa Unversity"
upper=lambda x:x.upper()
print(upper(text))

ADDIS ABABA UNVERSITY


In [35]:
# condition check using lambda function
evenOdd = lambda x: "Even" if x%2==0 else "odd"
print(evenOdd(4))
print(evenOdd(3))
print(evenOdd(10))
print(evenOdd(5))

Even
odd
Even
odd


In [36]:
# Numpy Revision
import numpy as np
arr=np.array([
    [2,3,4,6,7,7,3],
    [3,56,7,88,99,32,5],
     [3,10,37,45,32,12,6]
]
    
)
print(arr )
print("==========================================")
print(arr*2)
print("==========================================")
print(arr.shape)
print("==========================================")
arr2 = arr[:2, ::3]
print(arr2)
print("==========================================")
print(arr+1)
print("==========================================")
print(arr-10)
print("==========================================")
print(arr+arr)

[[ 2  3  4  6  7  7  3]
 [ 3 56  7 88 99 32  5]
 [ 3 10 37 45 32 12  6]]
[[  4   6   8  12  14  14   6]
 [  6 112  14 176 198  64  10]
 [  6  20  74  90  64  24  12]]
(3, 7)
[[ 2  6  3]
 [ 3 88  5]]
[[  3   4   5   7   8   8   4]
 [  4  57   8  89 100  33   6]
 [  4  11  38  46  33  13   7]]
[[-8 -7 -6 -4 -3 -3 -7]
 [-7 46 -3 78 89 22 -5]
 [-7  0 27 35 22  2 -4]]
[[  4   6   8  12  14  14   6]
 [  6 112  14 176 198  64  10]
 [  6  20  74  90  64  24  12]]


In [37]:
import numpy as np
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype = np.int64)
print(x.dtype)

int64
float64
int64


In [38]:
import numpy as np
arr1 = np.array([[4, 7], [2, 6]], dtype = np.int64)
arr2 = np.array([[3, 6], [2, 8]], dtype = np.int64) 

sum=np.add(arr1,arr2)
print(sum)

sum1=np.sum(arr1)
print(sum1)

sum2=np.sum(arr2)
print(sum2)

sqrt1=np.sqrt(arr1)
print(sqrt1)

[[ 7 13]
 [ 4 14]]
19
19
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [39]:
# Pandas Revision
import pandas as pd
data = {'Name':['Michael', 'Eyob', 'Bethelhem', 'Martha'],
 'Department':['Computer Science', 'InformationTechnology', 'Information Systems', 'Computer Engineering'],
 'Age':[20, 21, 19, 18]}
df=pd.DataFrame(data)
print(df)

        Name             Department  Age
0    Michael       Computer Science   20
1       Eyob  InformationTechnology   21
2  Bethelhem    Information Systems   19
3     Martha   Computer Engineering   18


In [40]:
# to print specific column from a dataframe use the following line of code
print("Öne Column")
print(df["Name"])

print("================================")
print("Two column")
print(df[["Name" , "Department"]])

print("================================")
print("Three column")
print(df[["Name" , "Department","Age"]])

Öne Column
0      Michael
1         Eyob
2    Bethelhem
3       Martha
Name: Name, dtype: object
Two column
        Name             Department
0    Michael       Computer Science
1       Eyob  InformationTechnology
2  Bethelhem    Information Systems
3     Martha   Computer Engineering
Three column
        Name             Department  Age
0    Michael       Computer Science   20
1       Eyob  InformationTechnology   21
2  Bethelhem    Information Systems   19
3     Martha   Computer Engineering   18


In [41]:
# To print  specific rows(Element) from a dataframe use the following line of code
print(df["Name"].loc[0])

print(df.loc[0])

print(df.loc[[0,1,2,3]])

Michael
Name                   Michael
Department    Computer Science
Age                         20
Name: 0, dtype: object
        Name             Department  Age
0    Michael       Computer Science   20
1       Eyob  InformationTechnology   21
2  Bethelhem    Information Systems   19
3     Martha   Computer Engineering   18


In [45]:
# to check the missing value from a data frame
# df["notNull"]=df.notnull()
# df["isnull"]=df.isnull()
df

,Name,Department,Age
0,Michael,Computer Science,20
1,Eyob,InformationTechnology,21
2,Bethelhem,Information Systems,19
3,Martha,Computer Engineering,18


In [47]:
import pandas as pd
import numpy as np
dict = {'First Score':[100, 90, np.nan, 95],
 'Second Score': [30, 45, 56, np.nan],
 'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(dict)
df.isnull()

,First Score,Second Score,Third Score
0,False,False,True
1,False,False,False
2,True,False,False
3,False,True,False


In [48]:
import pandas as pd
import numpy as np
data = {'First Score':[100, 90, np.nan, 95],
 'Second Score': [30, 45, 56, np.nan],
 'Third Score':[np.nan, 40, 80, 98]}
df = pd.DataFrame(data)


In [49]:
df

,First Score,Second Score,Third Score
0,100.0,30.0,NaN
1,90.0,45.0,40.0
2,NaN,56.0,80.0
3,95.0,NaN,98.0


In [53]:
df.isnull()

,First Score,Second Score,Third Score
0,False,False,True
1,False,False,False
2,True,False,False
3,False,True,False


In [54]:
df.isnull().sum()

First Score     1
Second Score    1
Third Score     1
dtype: int64

In [55]:
df.isnull().sum().sum()

np.int64(3)

In [58]:
# df.fillna(0)
df

,First Score,Second Score,Third Score
0,100.0,30.0,NaN
1,90.0,45.0,40.0
2,NaN,56.0,80.0
3,95.0,NaN,98.0


In [64]:
df["First Score"]=df["First Score"].fillna(df["First Score"].mean())
df["Second Score"]=df["Second Score"].fillna(df["Second Score"].mean())
df["Third Score"]=df["Third Score"].fillna(df["Third Score"].mean())

In [67]:
df.round(1)

,First Score,Second Score,Third Score
0,100.0,30.0,72.7
1,90.0,45.0,40.0
2,95.0,56.0,80.0
3,95.0,43.7,98.0


In [68]:
import pandas as pd
import numpy as np
dict = {'First Score':[100, 90, np.nan, 95],
 'Second Score': [30, np.nan, 45, 56],
 'Third Score':[52, 40, 80, 98],
 'Fourth Score':[np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
df

,First Score,Second Score,Third Score,Fourth Score
0,100.0,30.0,52,NaN
1,90.0,NaN,40,NaN
2,NaN,45.0,80,NaN
3,95.0,56.0,98,65.0


In [69]:
df.dropna()

,First Score,Second Score,Third Score,Fourth Score
3,95.0,56.0,98,65.0


In [75]:
# iteration in pandas dataframe 
import pandas as pd
data = {
    "Name": ["Abebe", "Hana", "Kebede"],
    "Age": [20, 22, 25],
    "Salary": [12000, 18000, 15000]
}
df = pd.DataFrame(data)
df

for col_name , col_data in df.items():
    print(col_name)
    print("=============")
    print(col_data)
    print("\n")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
for column, value in df.items():
    print("Column Name :", column)
    print(value)
    print("----------------")

Name
0     Abebe
1      Hana
2    Kebede
Name: Name, dtype: object


Age
0    20
1    22
2    25
Name: Age, dtype: int64


Salary
0    12000
1    18000
2    15000
Name: Salary, dtype: int64


$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
Column Name : Name
0     Abebe
1      Hana
2    Kebede
Name: Name, dtype: object
----------------
Column Name : Age
0    20
1    22
2    25
Name: Age, dtype: int64
----------------
Column Name : Salary
0    12000
1    18000
2    15000
Name: Salary, dtype: int64
----------------


In [83]:
for i, r in df.iterrows():
    print(i)
    print(r)

0
Name      Abebe
Age          20
Salary    12000
Name: 0, dtype: object
1
Name       Hana
Age          22
Salary    18000
Name: 1, dtype: object
2
Name      Kebede
Age           25
Salary     15000
Name: 2, dtype: object


In [84]:
import pandas as pd
dict = {'name':["Dereje", "Dagmawit", "Eyasu", "Yishak"],
 'degree': ["MBA", "BSC", "MSc", "PhD"],
 'score':[90, 40, 80, 98]}
df = pd.DataFrame(dict)
for i, j in df.iterrows():
 print(i, j)
 print()

0 name      Dereje
degree       MBA
score         90
Name: 0, dtype: object

1 name      Dagmawit
degree         BSC
score           40
Name: 1, dtype: object

2 name      Eyasu
degree      MSc
score        80
Name: 2, dtype: object

3 name      Yishak
degree       PhD
score         98
Name: 3, dtype: object



In [87]:
columns = list(df)
for i in columns:
 print (df[i][3])

Yishak
PhD
98


In [91]:
import pandas as pd
import matplotlib.pyplot as plt
data = {'Person ID': range(1, 13),
 'Full Name': ['Haileslassie Zeferu Abel', 'Worku Abenezer Girma', 'Abenezer Reta Tamirat', 'Abraham Melisew Fireda', 'Hailu Abraham Niguse', 'Weldetinsae Adonay Gebrehiwot ', 'Debebe Gebremeskel Akin', 'Teferi Amanuel Abebaw', 'Muche Amaniel Kahsu', 'Amanuel Degulaw Zerga', 'Amanuel Abate Nega', 'Amanuel Solomon Hailu'],
 'Income': [80000, 95000, 115000, 75000, 110000, 85000, 100000, 199000,105000, 90000, 80000, 95000]
}
df = pd.DataFrame(data)
df

plt.figure(figsize=(8, 4))
plt.boxplot(df['Income'], vert=False, showfliers=True)
plt.title('Box Plot of Incomes')
plt.xlabel('Income ($000)')
plt.show()

,Person ID,Full Name,Income
0,1,Haileslassie Zeferu Abel,80000
1,2,Worku Abenezer Girma,95000
2,3,Abenezer Reta Tamirat,115000
3,4,Abraham Melisew Fireda,75000
4,5,Hailu Abraham Niguse,110000
5,6,Weldetinsae Adonay Gebrehiwot,85000
6,7,Debebe Gebremeskel Akin,100000
7,8,Teferi Amanuel Abebaw,199000
8,9,Muche Amaniel Kahsu,105000
9,10,Amanuel Degulaw Zerga,90000
