In [1]:
import numpy as np 

In [2]:
Matrix=np.array([
    [10,20,30,40,50],
    [20,30,40,50,60]
])

In [3]:
print(Matrix)

[[10 20 30 40 50]
 [20 30 40 50 60]]


In [4]:
print(Matrix*2)

[[ 20  40  60  80 100]
 [ 40  60  80 100 120]]


In [6]:
print(Matrix.shape)

(2, 5)


In [8]:
Three_D_Array=np.array([
    [
       [10,20,30,40,50],
       [20,30,40,50,60]
        
    ],
    [
        [10,20,30,40,50],
        [20,30,40,50,60]
    ]
    
])

In [9]:
print(Three_D_Array.shape)

(2, 2, 5)


In [10]:
# Addational Example 

In [11]:
# Calculate mean of a given list
Grade=[69,89,98,78,89]

In [12]:
mean=np.mean(Grade)

In [13]:
print(mean)

84.6


In [14]:
# Calculate Maximum of a given list

In [15]:
maximum=np.max(Grade)

In [16]:
print(maximum)

98


In [17]:
# Calculate Minimum of a given list

In [18]:
minimum=np.min(Grade)

In [19]:
print(minimum)

69
