In [1]:
import numpy as np

In [2]:
arr=np.array(
    [
      [1, 2, 0, 4],
      [4, 5, 6, 0],
      [2, 0, 7, 8],
      [3, 7, 4, 2]  
    ]
)

In [3]:
arr_3=arr[1:]

In [4]:
print(arr_3)

[[4 5 6 0]
 [2 0 7 8]
 [3 7 4 2]]


In [5]:
arr_index=arr[:2 , ::3]
arr_1_4=arr[:1]
print(arr_1_4)

[[1 2 0 4]]


In [6]:

print(arr_index)
print(arr.copy)

[[1 4]
 [4 0]]
<built-in method copy of numpy.ndarray object at 0x000001E9A47E7270>


In [7]:
print(arr.dtype)

int64
