In [1]:
# Exercise 1: Display Information (0.2 marks)
print("Name: Nigus Admase")
print("Age: 25")
print("Favorite Programming Language: Python")

Name: Nigus Admase
Age: 25
Favorite Programming Language: Python


In [2]:
# # Exercise 2: Variables and Arithmetic Operations (0.2 marks)
# price = 100
# quantity = 10

# total_cost = price * quantity


# average_price = total_cost / quantity

# # Display results
# print("Total Cost:", total_cost)
# print("Average Price per Item:", average_price)

In [3]:
# # Exercise 3: User Input (0.2 marks)
# x=int(input("enter the first num:"))
# y=int(input("enter the secon num:"))
# def operator(x,y):
#     print("Sum:",x+y)
#     print("Differnce:", x-y)
#     print("Product:" , x*y)
# operator(x,y)

In [4]:
# Exercise 4: Conditional Statements (0.3 marks)
# score=int(input("Enter the score:"))
# if (score>50):
#     print("Pass")
# else:
#     print("Fail")

In [5]:
# Exercise 5: Multiple Conditions (0.3 marks)
# Given a student's mark:
mark = 45
if(mark>=80):
    print("A")
elif(mark>=70):
    print("B")
elif(mark>=60):
    print("C")
else:
    print("F")




F


In [6]:
# Exercise 6: For Loop (0.3 marks)
# Print numbers from 1 to 20 and display only the even numbers.
sum=0
for number in range(1,20):
    sum=sum+number
print("The Sum of Num from 1-20 is:" , sum)
    

The Sum of Num from 1-20 is: 190


In [7]:
# Exercise 7: While Loop (0.3 marks)

n = 1
total = 0
while n <= 100:
    total = total + n
    n += 1
print("Sum of numbers from 1 to 100:", total)

Sum of numbers from 1 to 100: 5050


In [8]:
# Exercise 8: Functions (0.3 marks)
def rectangle_area(length, width):
    area = length * width
    return area
#calling the function
print("Area of rectangle:",rectangle_area(23,10))

Area of rectangle: 230


In [9]:
# Exercise 9: Lambda Function (0.3 marks)
lambda_func = lambda x: x**2
# for x in range(1,11):
     # print("The Square of", x,"is:" ,lambda_func(x))

In [10]:
# Exercise 10: List Comprehension (0.4 marks)

squares = [num ** 2 for num in range(1, 21)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [11]:
# Section B: NumPy
# Exercise 11: Creating Arrays (0.4 marks)
# Create a NumPy array containing numbers 1–20.
import numpy as np

number=np.array(range(1,21))
# Display:
print(number)
# Shape
print(number.shape)
# Data type
print(number.dtype)
# Size
print(number.size)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
(20,)
int64
20


In [12]:
# Exercise 12: Array Operations (0.4 marks)
a=np.array([10,20,30,40])
b=np.array([5,10,15,20])
# Addition
print(a+b)
# Subtraction
print(a-b)
# Multiplication
print(a*b)
# Division
print(a/b)

[15 30 45 60]
[ 5 10 15 20]
[ 50 200 450 800]
[2. 2. 2. 2.]


In [13]:
# Exercise 13: Statistics Using NumPy (0.5 marks)
# For an array of exam scores:
import numpy as np
Exam_Score=np.array([50.67,45,98,82,89])
# Find the mean
mean_score=np.mean(Exam_Score)
print("The Average score : " ,mean_score)
# Find the maximum value.
max_score=np.max(Exam_Score)
print("The Maximum score : " ,max_score)
# Find the minimum value.
min_score=np.min(Exam_Score)
print("The Minimum score : " ,min_score)
# Find the standard deviation.
Std_score=np.std(Exam_Score)
print("The STD score : " ,Std_score)

The Average score :  72.934
The Maximum score :  98.0
The Minimum score :  45.0
The STD score :  21.187765903936167


In [14]:
# Section C: Pandas DataFrames
# Exercise 14: Create a DataFrame (0.5 marks)
# Create a DataFrame containing:
import pandas as pd
# Student Name
# Age
# Score
df=pd.DataFrame({
    "Student-Name":["Abebe","Hewan","Selam","Natan","Aman","abdu"],
    "Age":[24,23,26,25,23,22],
    "Score":[88,78,65,98,76,43]
})
# Display the first three rows.
print(df.head(3))

  Student-Name  Age  Score
0        Abebe   24     88
1        Hewan   23     78
2        Selam   26     65


In [15]:
# Exercise 15: Selecting Rows and Columns (0.5 marks)
# Using a DataFrame:
# Display only the Name column.
print(df["Student-Name"])
# Display students whose score is greater than 70.
print(df[df["Score"]>70])

0    Abebe
1    Hewan
2    Selam
3    Natan
4     Aman
5     abdu
Name: Student-Name, dtype: object
  Student-Name  Age  Score
0        Abebe   24     88
1        Hewan   23     78
3        Natan   25     98
4         Aman   23     76


In [16]:
# Exercise 16: Adding New Columns (0.5 marks)
# Create a column called Status .

# Assign:
# "Pass" for scores ≥ 50.
# "Fail" otherwise.
df["Status"]=df["Score"].apply(
    lambda x: "Pass" if x>=50 else "Fail"
)

In [17]:
print(df)

  Student-Name  Age  Score Status
0        Abebe   24     88   Pass
1        Hewan   23     78   Pass
2        Selam   26     65   Pass
3        Natan   25     98   Pass
4         Aman   23     76   Pass
5         abdu   22     43   Fail


In [18]:
# Exercise 17: Summary Statistics (0.6 marks)
# Using .describe() :
print(df.describe())
# Display:
# Mean
# Standard deviation
# Minimum
# Maximum values

             Age      Score
count   6.000000   6.000000
mean   23.833333  74.666667
std     1.471960  19.138095
min    22.000000  43.000000
25%    23.000000  67.750000
50%    23.500000  77.000000
75%    24.750000  85.500000
max    26.000000  98.000000


In [19]:
# Section D: Data Cleaning
# Exercise 18: Missing Values Detection (0.6 marks)
# Create a DataFrame containing missing values.
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Abebe", "Sara", "John", None, "Mekdes", "Daniel"],
    "Age": [20, 21, None, 22, 19, 23],
    "Score": [85, None, 78, 90, None, 88],
    "Department": ["IT", "CS", None, "IT", "SE", "CS"],
    "Attendance": [95.5, 88.0, 92.5, None, 85.0, None]
})
print(df)
# Write code to determine:
# Number of missing values in each column.
print(df.isnull().sum())
# Total missing values in the dataset.
print("========================")
print("Total missing Value:",df.isnull().sum().sum())

   Student_ID    Name   Age  Score Department  Attendance
0         101   Abebe  20.0   85.0         IT        95.5
1         102    Sara  21.0    NaN         CS        88.0
2         103    John   NaN   78.0       None        92.5
3         104    None  22.0   90.0         IT         NaN
4         105  Mekdes  19.0    NaN         SE        85.0
5         106  Daniel  23.0   88.0         CS         NaN
Student_ID    0
Name          1
Age           1
Score         2
Department    1
Attendance    2
dtype: int64
Total missing Value: 7


In [20]:
# Exercise 19: Handling Missing Values (0.7 marks)
# Replace missing numerical values using:

# ==========================
# Mean replacement
# ==========================

df_mean = df.copy()

# Fill missing numerical values with mean
df_mean["Age"] = df_mean["Age"].fillna(df_mean["Age"].mean())
df_mean["Score"] = df_mean["Score"].fillna(df_mean["Score"].mean())
df_mean["Attendance"] = df_mean["Attendance"].fillna(
    df_mean["Attendance"].mean()
)

print("DataFrame after Mean replacement:")
print(df_mean)


print("========================================")


# ==========================
# Median replacement
# ==========================

df_median = df.copy()

# Fill missing numerical values with median
df_median["Age"] = df_median["Age"].fillna(df_median["Age"].median())
df_median["Score"] = df_median["Score"].fillna(df_median["Score"].median())
df_median["Attendance"] = df_median["Attendance"].fillna(
    df_median["Attendance"].median()
)

print("DataFrame after Median replacement:")
print(df_median)


print("========================================")


# Compare Mean vs Median results

comparison = pd.DataFrame({
    "Mean Replacement": [
        df["Age"].mean(),
        df["Score"].mean(),
        df["Attendance"].mean()
    ],
    "Median Replacement": [
        df["Age"].median(),
        df["Score"].median(),
        df["Attendance"].median()
    ]
})

print("Comparison:")
print(comparison)

DataFrame after Mean replacement:
   Student_ID    Name   Age  Score Department  Attendance
0         101   Abebe  20.0  85.00         IT       95.50
1         102    Sara  21.0  85.25         CS       88.00
2         103    John  21.0  78.00       None       92.50
3         104    None  22.0  90.00         IT       90.25
4         105  Mekdes  19.0  85.25         SE       85.00
5         106  Daniel  23.0  88.00         CS       90.25
DataFrame after Median replacement:
   Student_ID    Name   Age  Score Department  Attendance
0         101   Abebe  20.0   85.0         IT       95.50
1         102    Sara  21.0   86.5         CS       88.00
2         103    John  21.0   78.0       None       92.50
3         104    None  22.0   90.0         IT       90.25
4         105  Mekdes  19.0   86.5         SE       85.00
5         106  Daniel  23.0   88.0         CS       90.25
Comparison:
   Mean Replacement  Median Replacement
0             21.00               21.00
1             85.25       

In [21]:
# Exercise 20: Duplicate Records (0.7 marks)
# Create a dataset containing duplicate rows.
import pandas as pd
df = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 102, 106],
    "Name": ["Abebe", "Sara", "John", "Mekdes", "Daniel", "Sara", "Helen"],
    "Age": [20, 21, 22, 19, 23, 21, 20],
    "Score": [85, 90, 78, 88, 92, 90, 80],
    "Department": ["IT", "CS", "SE", "IT", "CS", "CS", "IT"]
})
print(df)

# Identify duplicates.
print("============================")
print(df.duplicated())
# Remove duplicate records.
print(df.drop_duplicates())


   Student_ID    Name  Age  Score Department
0         101   Abebe   20     85         IT
1         102    Sara   21     90         CS
2         103    John   22     78         SE
3         104  Mekdes   19     88         IT
4         105  Daniel   23     92         CS
5         102    Sara   21     90         CS
6         106   Helen   20     80         IT
0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool
   Student_ID    Name  Age  Score Department
0         101   Abebe   20     85         IT
1         102    Sara   21     90         CS
2         103    John   22     78         SE
3         104  Mekdes   19     88         IT
4         105  Daniel   23     92         CS
6         106   Helen   20     80         IT


In [22]:
# Exercise 21: Standardizing Text Data (0.8 marks)
# Given inconsistent city names:
df=pd.DataFrame({
    "Adress":["addis ababa", "ADDIS ABABA", "Addis Ababa", "adDis abaBa"]
})
df["Standard_text"]=(df["Adress"].str.title())
# Convert them into a consistent format.
print(df)

        Adress Standard_text
0  addis ababa   Addis Ababa
1  ADDIS ABABA   Addis Ababa
2  Addis Ababa   Addis Ababa
3  adDis abaBa   Addis Ababa


In [23]:
# Exercise 22: Correcting Data Entry Errors (0.8 marks)
# Given ages:
df=pd.DataFrame({
    "Age":[21, 25, 230, 30, 19, -5, 27]
    
})
# Identify invalid values and replace them with missing values ( NaN ).
df["Age"] = df["Age"].apply(
    lambda x: np.nan if x < 0 or x > 120 else x
)

In [26]:
# Section E: Integrated Data Wrangling
# Exercise 23: Cleaning a Customer Dataset (1 mark)
import pandas as pd
import numpy as np

# Create dataset with:
# - Missing values
# - Duplicate rows
# - Inconsistent text

df = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 104, 105],
    "Name": ["John", "mary", "DAVID", "Sara", "Sara", "Mike"],
    "City": ["Addis Ababa", "addis ababa", "ADDIS ABABA", None, "Addis Ababa", "Bahir Dar"],
    "Age": [25, 30, np.nan, 28, 28, 35]
})

print("Original Dataset:")
print(df)


# -------------------------------
# Cleaning Process
# -------------------------------

# 1. Remove duplicate rows
df = df.drop_duplicates()


# 2. Handle missing values
# Fill missing city with "Unknown"
df["City"] = df["City"].fillna("Unknown")

# Fill missing age with mean age
df["Age"] = df["Age"].fillna(df["Age"].mean())


# 3. Fix inconsistent text
# Convert names to proper case
df["Name"] = df["Name"].str.title()

# Convert city names to proper case
df["City"] = df["City"].str.title()


print("\nCleaned Dataset:")
print(df)

Original Dataset:
   Customer_ID   Name         City   Age
0          101   John  Addis Ababa  25.0
1          102   mary  addis ababa  30.0
2          103  DAVID  ADDIS ABABA   NaN
3          104   Sara         None  28.0
4          104   Sara  Addis Ababa  28.0
5          105   Mike    Bahir Dar  35.0

Cleaned Dataset:
   Customer_ID   Name         City   Age
0          101   John  Addis Ababa  25.0
1          102   Mary  Addis Ababa  30.0
2          103  David  Addis Ababa  29.2
3          104   Sara      Unknown  28.0
4          104   Sara  Addis Ababa  28.0
5          105   Mike    Bahir Dar  35.0


In [27]:
import pandas as pd

# Sales dataset
sales = pd.Series([100, 120, 130, 150, 160, 170, 180, 190, 200, 500])

# Calculate Q1 and Q3
Q1 = sales.quantile(0.25)
Q3 = sales.quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = sales[(sales < lower_bound) | (sales > upper_bound)]

# Display results
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

print("\nOutlier Values:")
print(outliers)

Q1: 135.0
Q3: 187.5
IQR: 52.5
Lower Bound: 56.25
Upper Bound: 266.25

Outlier Values:
9    500
dtype: int64


In [28]:
import pandas as pd
import numpy as np

# ---------------------------------------
# Create dataset with data problems
# ---------------------------------------

df = pd.DataFrame({
    "Customer_ID": [101, 102, 103, 104, 104, 105, 106],
    "Name": ["john", "MARY", "David", "sara", "sara", "MIKE", "Alex"],
    "City": ["addis ababa", "ADDIS ABABA", None, "Bahir dar", "Bahir dar", "dire dawa", "Addis Ababa"],
    "Sales": [500, 600, 700, 650, 650, 550, 10000]
})

print("Original Dataset:")
print(df)


# ---------------------------------------
# 1. Detect Missing Values
# ---------------------------------------

print("\nMissing Values:")
print(df.isnull().sum())


# ---------------------------------------
# 2. Fill Missing Values
# ---------------------------------------

# Fill missing city
df["City"] = df["City"].fillna("Unknown")


# ---------------------------------------
# 3. Remove Duplicate Records
# ---------------------------------------

df = df.drop_duplicates()


# ---------------------------------------
# 4. Standardize Text Values
# ---------------------------------------

df["Name"] = df["Name"].str.title()
df["City"] = df["City"].str.title()


# ---------------------------------------
# 5. Detect Outliers Using IQR
# ---------------------------------------

Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1


lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


print("\nLower Bound:", lower_bound)
print("Upper Bound:", upper_bound)


# Display outliers
outliers = df[
    (df["Sales"] < lower_bound) |
    (df["Sales"] > upper_bound)
]

print("\nOutliers:")
print(outliers)


# ---------------------------------------
# 6. Remove/Capping Outliers
# ---------------------------------------

# Cap extreme values instead of deleting
df["Sales"] = np.where(
    df["Sales"] > upper_bound,
    upper_bound,
    df["Sales"]
)


# ---------------------------------------
# 7. Display Final Clean Dataset
# ---------------------------------------

print("\nFinal Cleaned Dataset:")
print(df)

Original Dataset:
   Customer_ID   Name         City  Sales
0          101   john  addis ababa    500
1          102   MARY  ADDIS ABABA    600
2          103  David         None    700
3          104   sara    Bahir dar    650
4          104   sara    Bahir dar    650
5          105   MIKE    dire dawa    550
6          106   Alex  Addis Ababa  10000

Missing Values:
Customer_ID    0
Name           0
City           1
Sales          0
dtype: int64

Lower Bound: 375.0
Upper Bound: 875.0

Outliers:
   Customer_ID  Name         City  Sales
6          106  Alex  Addis Ababa  10000

Final Cleaned Dataset:
   Customer_ID   Name         City  Sales
0          101   John  Addis Ababa  500.0
1          102   Mary  Addis Ababa  600.0
2          103  David      Unknown  700.0
3          104   Sara    Bahir Dar  650.0
5          105   Mike    Dire Dawa  550.0
6          106   Alex  Addis Ababa  875.0
